bite/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'),name="home1"),




]

myapp/urls.py
from django.urls import path,re_path
from myapp import views

app_name = "myapp"
urlpatterns=[
    path('',views.home,name='home'),
    path("register/",views.register,name="register"),
    path('user_login/',views.user_login,name='login'),
    path("logout/",views.user_logout,name='logout'),
    path('about_us/',views.about_us,name='about_us'),
    path('food_list/',views.food_list,name='food_list'),
    path('create/',views.FoodCreateView.as_view(),name='create'),
    re_path(r'^food/(?P<pk>\d+)/update/$',views.FoodUpdateView.as_view(),name="update_food"),
    re_path(r'^food/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name="food_remove"),
    re_path(r'^add_to_cart/(?P<pk>\d+)/$',views.cart,name="cart"),
    re_path(r'^your_cart/(?P<pk>\d+)/$',views.adding_to_cart,name="your_cart"),
    re_path(r'^your_cart/(?P<pk>\d+)/delete/$',views.clear_cart,name="your_cart_delete"),
    re_path(r'^your_cart/(?P<pk>\d+)/order/$',views.order_creating,name="your_cart_order"),
    re_path(r'^orders/$',views.your_orders,name="your_order"),
    re_path(r'^orders/(?P<pk>\d+)/$',views.change_status,name="change_status"),
    re_path(r'^cart/(?P<pk>\d+)/delete/$',views.cart_delete,name="cart_delete"),

]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
User_CHOICES = (
    ('shop','Vendor'),
    ('buyer', 'Customer')
)
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete='CASCADE',related_name='type')
    type_user=models.CharField(max_length=10, choices=User_CHOICES,blank=False)


class Food(models.Model):
    user=models.ForeignKey('auth.User',on_delete='CASCADE',related_name='foods')
    food_name=models.CharField(max_length=25,blank=False)
    food_type=models.CharField(max_length=25)
    food_rate=models.PositiveIntegerField()
    def get_absolute_url(self):
        return reverse('myapp:food_list')
class Add_to_cart(models.Model):
    customer=models.ForeignKey('auth.User',on_delete='CASCADE',related_name='customer')
    vendor=models.ForeignKey(Food,on_delete="",related_name='vendors')
class Orders(models.Model):
    customer=models.CharField(max_length=25)
    vendor=models.CharField(max_length=25)
    food_name=models.CharField(max_length=25)
    food_rate=models.CharField(max_length=25)
    food_type=models.CharField(max_length=25)
    order_status=models.CharField(max_length=25)
    date_field=models.DateField(auto_now=True)

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from myapp.models import UserProfileInfo,Food



class UserForm(forms.ModelForm):
    #username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    ##first_name= forms.CharField()
    #last_name= forms.CharField()
    #email = forms.EmailField()
    class Meta():
        model=User
        fields = ('username','password','first_name','last_name','email')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields = ('type_user',)
class FoodForm(forms.ModelForm):
    class Meta():
        model=Food
        fields = ('food_name','food_type','food_rate')

myapp/views.py
from django.shortcuts import render,get_object_or_404
from myapp.forms import UserForm,UserProfileInfoForm,FoodForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from myapp.models import UserProfileInfo,Food,Add_to_cart,Orders
from . import models
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.models import User
# Create your views here.
def about_us(request):

    return render(request,'myapp/aboutus.html',{})
def food_list(request):

    return render(request,'myapp/food_list.html',{})
def home(request):
    data = User.objects.all()



    return render(request,'myapp/base.html',{'data':data,})
def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile= profile_form.save(commit=False)
            profile.user=user

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:

        user_form =UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'registration/registration.html',{
                                    'user_form':user_form,
                                    'profile_form':profile_form,
                                    'registered':registered,
    })
def user_login(request):
    if request.method=='POST':

        username=request.POST.get('username')

        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        #print("USER",user.first_name)
        if user:
            if user.is_active:
                login(request,user)
                #print("USER",UserProfileInfo.objects.get(user=user).type_user)
                return HttpResponseRedirect(reverse('myapp:home'))
            else:
                user=False
                return render(request,'registration/login.html',{'user':user})
        else:
            print("Some tried to fail")
            print("Username",username,"Pass",password)
            user=False
            return render(request,'registration/login.html',{'user':user})
    else:
        return render(request,'registration/login.html',{})
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:home'))
class FoodCreateView(LoginRequiredMixin,CreateView):
    #login_url='/login/'
    redirect_field_name = "food_list.html"
    form_class = FoodForm
    model = Food
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
class FoodUpdateView(LoginRequiredMixin,UpdateView):
    login_url='/login/'
    redirect_field_name = "food_list.html"
    form_class = FoodForm
    model = Food
class PostDeleteView(LoginRequiredMixin,DeleteView):

    model = Food
    success_url = reverse_lazy('myapp:food_list')



@login_required
def cart(request,pk):
    food = get_object_or_404(Food,pk=pk)
    print(food.food_name)
    print(food.user)
    print(request.user)
    c=Add_to_cart(customer=request.user,vendor=food)
    c.save()


    return HttpResponseRedirect(reverse('myapp:home'))
@login_required
def adding_to_cart(request,pk):
    data = Add_to_cart.objects.all()
    total=0
    for i in data:
        if i.customer==request.user:
            total=total+i.vendor.food_rate
        #else:
            #print(total)
            #print(i.customer,request.user.username,request.user)
            #total=789
    #print(i.vendor.food_name,i.vendor.food_rate,i.vendor.user)
    #print(request.user.username)
    #print(i.customer)
    #Add_to_cart.objects.all().delete()
    return render(request,'myapp/cart_added.html',{'data':data,'total':total,})
@login_required
def clear_cart(request,pk):
    Add_to_cart.objects.all().delete()
    return HttpResponseRedirect(reverse('myapp:home'))
@login_required
def order_creating(request,pk):
    #Orders.objects.all().delete()
    data = Add_to_cart.objects.all()
    for i in data:
        if i.customer==request.user:
            ob=Orders(customer=request.user,vendor=i.vendor.user,food_name=i.vendor.food_name,food_rate=i.vendor.food_rate,food_type=i.vendor.food_type,order_status="Pending")
            ob.save()
    Add_to_cart.objects.all().delete()
    return HttpResponseRedirect(reverse('myapp:your_order'))
@login_required
def your_orders(request):
    dat=Orders.objects.all()
    for data in dat:
        print(data.customer)
        print(data.vendor)
        print(data.food_name)
        print(data.food_rate)
        print(data.food_type)
        print(data.order_status)
        print(data.date_field)
        print()
    return render(request,'myapp/orders.html',{'data':dat,})
@login_required
def change_status(request,pk):
    a=Orders.objects.get(pk=pk)
    a.order_status="Completed"
    a.save()
    print(a.order_status)
    return HttpResponseRedirect(reverse('myapp:your_order'))
@login_required
def cart_delete(request,pk):
    Add_to_cart.objects.exclude(pk=pk)
    return HttpResponseRedirect(reverse('myapp:your_cart',kwargs={'pk':request.user.pk}))

myapp/templates/myapp/aboutus.html
<!DOCTYPE html>

{% extends "myapp/base.html" %}
{% block body_block %}
{% load staticfiles %}
<div class="container">
  <hr>
  <h2>AboutUs</h2>
<hr>
<div class="row">
    <div class="col" style="margin-left:100px;">
      <div class="card text-dark" style="width: 22rem;">
  <!-- img src="{% static "images/safura.jpg"%}" class="card-img-top" alt="..."-->
  <div class="card-body">
    <h2 class="card-title">SAFURA ZAHEER</h2>
    </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">INFORMATION TECHNOLOGY</li>
    <li class="list-group-item">IET LUCKNOW</li>
    <li class="list-group-item">FRONT END DEVLOPER</li>
  </ul>
  <div class="card-body">
    <a href="https://www.facebook.com/safura.zaheer.7" target="_blank" class="card-link">Facebook</a>
    <a href="https://www.linkedin.com/in/safura-zaheer-8a320714b/" target="_blank"class="card-link">LinkdIn</a>
  </div>
</div>

    </div>
    <div class="col">
      <div class="card text-dark" style="width: 22rem;">
  <!-- img src="{% static "images/saurabh.jpg"%}" class="card-img-top" alt="..."-->
  <div class="card-body">
    <h2 class="card-title">SAURABH SINGH</h2>
    </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">INFORMATION TECHNOLOGY</li>
    <li class="list-group-item">IET LUCKNOW</li>
    <li class="list-group-item">BACK END DEVLOPER</li>
  </ul>
  <div class="card-body">
    <a href="https://www.facebook.com/profile.php?id=100006109419616" target="_blank" class="card-link">Facebook</a>
    <a href="https://www.linkedin.com/in/saurabh-singh-ba5301158/" target="_blank" class="card-link">LinkdIn</a>
  </div>
</div>

    </div>


  </div>
  </div>

{% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BiTe</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>
  <body style="background-color: #d9cccf;">
    <!-- NAV BAR STARTS HERE -->

    <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'myapp:home' %}">BiTe</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarText">
    <!--ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul-->
      <ul class='navbar-nav mr-auto'>
          <li class="nav-item"><a href="{% url 'myapp:about_us' %}" class="nav-link">AboutUs</a></li>
      </ul>

      <ul class='navbar-nav ml-auto'>


        {% if user.is_authenticated %}
          {% if user.type.type_user == "shop" %}
        <li class="nav-item"><a href="{% url 'myapp:create'%}" class="nav-link">Add_DISH</a></li>
        {% else %}
        <li class="nav-item"><a href="{% url 'myapp:your_cart' pk=user.pk %}" class="nav-link">Your_Cart</a></li>
        {% endif %}
        <li class="nav-item"><a href="{% url 'myapp:your_order' %}" class="nav-link">Orders</a></li>


        <li class="nav-item"><a href="{% url 'myapp:food_list' %}" class="nav-link">Hi, {{ user.first_name }}</a></li>
        <li class="nav-item"><a href="{% url 'myapp:logout' %}" class="nav-link">LogOut</a></li>
        {% else %}
        <li class="nav-item"><a href="{% url 'myapp:login' %}" class="nav-link">LogIn</a></li>
        <li class="nav-item"><a href="{% url 'myapp:register' %}" class="nav-link">Register</a></li>
        {% endif %}



      </ul>

  </div>
</nav>

    <!-- NAV BAR ENDS HERE -->
<hr>
<hr>
<hr>
<hr>
    {% block body_block %}

    <div class="container">
      <div class="jumbotron">
        <h2>Welcome To Home page of bite.com</h2>
        {% if user.is_authenticated %}
        <h2>Hello {{ user.first_name }} {{ user.last_name }}</h2>
        {% if user.type.type_user == "shop" %}
          <h3>Add New Food To Your Menu to increase your business</h3>
          {% else %}
          <h3>Order Your Food Now</h3>
<!-- PAGE WHERE CUSTOMER CAN SEE AVAILABLE FOOD -->

    <fieldset>
      {% for d in data %}
        {% if d.type.type_user == "shop" %}
          <h1></h1>
          <ul class="list-group">
              <li class="list-group-item active">{{ d.username }}</li>
                <!-- FROM HERE TO HERE -->

                {% for fo in d.foods.all %}
                {% if not forloop.counter|divisibleby:2 %}
                <hr>
                <div class="row" style="margin-left:120px;">

                {% endif %}

                <div class="cols card" style="margin-left:95px;" >

                  <div class="card-body" style="width: 18rem;">
                    <h5 class="card-title">{{ fo.food_name|upper }}</h5>
                    <p class="card-text">Food Type : {{ fo.food_type|capfirst }}</p>
                    <p class="card-text">Rate : {{ fo.food_rate }} INR</p>
                    <a href="{% url 'myapp:cart' pk=fo.pk %}" class="btn btn-primary">ADD TO CART</a>

                  </div>
                </div>
                {% if forloop.counter|divisibleby:2 %}

                </div>
                  {% endif %}

                {% endfor %}



              <!-- HERE  -->
              </ul>
        {% endif %}
      {% endfor %}

    </fieldset>










  <!--UPTO HAERE -->
          {% endif %}
          {% else %}

          <h3>Login or Register  first to visit Site</h3>
          {% endif %}


      </div>
    </div>
    {% endblock %}

  </body>
</html>

myapp/templates/myapp/cart_added.html
<!DOCTYPE html>

{% extends "myapp/base.html" %}
{% block body_block %}


<div class="container">
  {% if user.is_authenticated %}


    {% if user.type.type_user == "buyer" %}

      <ul class="list-group">
        <hr>
        <li class="list-group-item active">Your Cart</li>
        {% for d in data %}

          {% if d.customer == user %}
        <li class="list-group-item">{{ d.vendor.user.username }}   {{d.vendor.food_name}}  {{ d.vendor.food_rate }} <a href="{% url 'myapp:cart_delete' pk=d.pk %}" class="btn btn-primary">DELETE</a> </li>


          {% endif %}
        {% endfor %}
      </ul>
      <hr>
      <li class="list-group-item active" ><h2 style="margin-left:13em;">Total        :            {{ total }} INR</h2></li>
      <hr>
      <div style="margin-left:26em;">
        <a href="{% url 'myapp:your_cart_delete' pk=user.pk %}" class="btn btn-primary">Clear Cart</a>
        <a href="{% url 'myapp:your_cart_order' pk=user.pk %}" class="btn btn-primary" style="margin-left:30px;">Order Now</a>
      </div>
<!-- your_cart -->
<hr>
    {% endif %}
  {% else %}
    <ul class="list-group">
      <li class="list-group-item active"> Nothing to Display</li>

    </ul>

{% endif %}

</div>








{% endblock %}

myapp/templates/myapp/food_confirm_delete.html
<!DOCTYPE html>

{% extends "myapp/base.html" %}
{% block body_block %}

<div class="container">


<form class=""  method="post">
    {% csrf_token %}
    <h3>On Clicking Confirm</h3>
    <h4>ITEM : {{ object.food_name }} ITEM TYPE : {{ object.food_type }} ITEM PRICE: {{ object.food_rate }}</h4>
    <h4>Will be Deleted</h4>
    <input type="submit" name="" value="Confirm" class='btn btn-danger'>

  </form>

</div>

{% endblock %}

myapp/templates/myapp/food_form.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}
{% block body_block %}
<div class="container">
  {% if not form.instance.pk %}
  <h2>Create Food</h2>
  {% else %}
  <h2>Update Food</h2>
  {% endif %}

      <form class="post-form"  method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-primary">Submit</button>

      </form>
</div>






{% endblock %}

myapp/templates/myapp/food_list.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}
{% block body_block %}
<div class="container">
  {% if user.is_authenticated %}
  {% if user.type.type_user == "shop" %}
    <h3 style="margin-top:20px;"> Hi... {{ user.first_name }}</h3>
    <h4>Foods Provided by You</h4>

      {% for fo in user.foods.all %}
    {% if not forloop.counter|divisibleby:2 %}
    <hr>
      <div class="row" style="margin-left:120px;">

      {% endif %}

      <div class="cols card" style="margin-left:95px;" >

        <div class="card-body" style="width: 18rem;">
          <h5 class="card-title">{{ fo.food_name|upper }}</h5>
          <p class="card-text">Food Type : {{ fo.food_type|capfirst }}</p>
          <p class="card-text">Rate : {{ fo.food_rate }} INR</p>
          <a href="{% url 'myapp:update_food' pk=fo.pk %}" class="btn btn-primary">Update</a>
          <a href="{% url 'myapp:food_remove' pk=fo.pk %}" class="btn btn-primary" style="margin-left:30px;">Delete</a>
        </div>
      </div>
      {% if forloop.counter|divisibleby:2 %}

    </div>
        {% endif %}

      {% endfor %}


  {% else %}
      <h1>{{ user.first_name }}, Thanks for using Bite.com </h1>
      {% endif %}
  {% else %}
  <h1>You have to LogIn or Register first</h1>
  {% endif %}
</div>






{% endblock %}

myapp/templates/myapp/orders.html
<!DOCTYPE html>

{% extends "myapp/base.html" %}
{% block body_block %}
<div class="container">


<hr>
{% if user.is_authenticated %}
<ul class="list-group">
    <li class="list-group-item active"><h1 style="margin-left:10em;">Your Orders</h1></li>



          {% if user.type.type_user == "buyer" %}
          <hr>
                  <table  border="1">
                    <tr style="text-align:center;">
                      <th>DATE</th>
                      <th>ORDERED FROM</th>
                      <th>ORDERED FOOD</th>
                      <th>FOOD RATE</th>
                      <th>STATUS </th>
                    </tr>
                  {% for da in data %}
                  <tr style="text-align:center;">
                    <td>{{ da.date_field }}</td>
                    <td>{{ da.vendor }}</td>
                    <td>{{ da.food_name }}</td>
                    <td>{{ da.food_rate }}</td>
                    <td>{{ da.order_status}}</td>
                  </tr>


                  {% endfor %}
                  </table>




          {% else %}


          <hr>
                  <table  border="1">
                    <tr style="text-align:center;">
                      <th>DATE</th>
                      <th>ORDERED FROM</th>
                      <th>ORDERED FOOD</th>
                      <th>FOOD RATE</th>
                      <th>STATUS </th>
                    </tr>
                  {% for da in data %}
                  <tr style="text-align:center;">
                    <td>{{ da.date_field }}</td>
                    <td>{{ da.customer }}</td>
                    <td>{{ da.food_name }}</td>
                    <td>{{ da.food_rate }}</td>
                    {% if da.order_status == "Pending" %}
                    <td><a href="{% url 'myapp:change_status' pk=da.pk %}">{{ da.order_status }}</a></td>
                    {% else %}
                    <td>{{ da.order_status }}</td>
                    {% endif %}
                  </tr>


                  {% endfor %}
                  </table>














          {% endif %}



{% endif %}




</div>
{% endblock %}